### ISSUE TITLE
Allowed to set UserAgent on client

### ISSUE THREAD

**Issue by fieg** [treehouselabs/keystone-client#8]
It would be nice if our projects using the keystone client can set the user agent, so that in, for example, out getgeo access log we see which projects/clients are doing the requests.

**Comment by pkruithof** [comment]
It's possible to pass Guzzle configuration to the factory method since version 2.0, it would look like this:

```php
$client = $factory->createClient($tenant, ['headers' => ['User-Agent' => 'Foo/1.0']]);
```
